apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-payment-app
  namespace: saleor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-payment-app
  template:
    metadata:
      labels:
        app: dummy-payment-app
    spec:
      containers:
      - name: dummy-payment-app
        image: dummy-payment-app:latest
        env:
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: env
                key: BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-payment-app
  namespace: saleor
spec:
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: dummy-payment-app
