apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-payment-app
  labels:
    app: dummy-payment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-payment-app
  template:
    metadata:
      labels:
        app: dummy-payment-app
    spec:
      containers:
        - name: dummy-payment-app
          image: dummy-payment-app
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: SALEOR_API_URL
              value: http://host.docker.internal:8000/graphql/
            - name: APP_URL
              value: http://localhost:30081
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-payment-app
  labels:
    app: dummy-payment-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30081
  selector:
    app: dummy-payment-app
