apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-frontend
  labels:
    app: saleor-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-frontend
  template:
    metadata:
      labels:
        app: saleor-frontend
    spec:
      containers:
        - name: saleor-frontend
          image: saleor-frontend
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: NEXT_PUBLIC_SALEOR_API_URL
              value: http://host.docker.internal:8000/graphql/
            - name: NEXT_PUBLIC_STOREFRONT_URL
              value: http://localhost:30080
            - name: HOST
              value: "0.0.0.0"
            - name: IMAGES_DOMAIN
              value: "host.docker.internal"
            - name: NEXT_PUBLIC_IMAGES_URL
              value: http://host.docker.internal:8000
            - name: NEXT_PUBLIC_CHECKOUT_URL
              value: http://localhost:30080/checkout
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-frontend
  labels:
    app: saleor-frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: saleor-frontend
