apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleor-frontend
  template:
    metadata:
      labels:
        app: saleor-frontend
    spec:
      containers:
      - name: saleor-frontend
        image: saleor-frontend:latest
        env:
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: env
                key: BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: saleor-frontend
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: saleor-frontend
